// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyAMIS.Migrations
{
    [DbContext(typeof(MyAMISContext))]
    [Migration("20260429014843_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyAMIS.Core.Entidades.Activo", b =>
                {
                    b.Property<int>("idActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idActivo"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("estadoActivold")
                        .HasColumnType("integer");

                    b.Property<string>("marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("tipoActivold")
                        .HasColumnType("integer");

                    b.HasKey("idActivo");

                    b.HasIndex("estadoActivold");

                    b.HasIndex("tipoActivold");

                    b.ToTable("Activo");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.EstadoActivo", b =>
                {
                    b.Property<int>("idEstadoActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idEstadoActivo"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idEstadoActivo");

                    b.ToTable("EstadoActivo");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.TipoActivo", b =>
                {
                    b.Property<int>("idTipoActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTipoActivo"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idTipoActivo");

                    b.ToTable("TipoActivo");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.Activo", b =>
                {
                    b.HasOne("MyAMIS.Core.Entidades.EstadoActivo", "EstadoActivo")
                        .WithMany("Activos")
                        .HasForeignKey("estadoActivold")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAMIS.Core.Entidades.TipoActivo", "TipoActivo")
                        .WithMany("Activos")
                        .HasForeignKey("tipoActivold")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoActivo");

                    b.Navigation("TipoActivo");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.EstadoActivo", b =>
                {
                    b.Navigation("Activos");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.TipoActivo", b =>
                {
                    b.Navigation("Activos");
                });
#pragma warning restore 612, 618
        }
    }
}
