// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyAMIS.Migrations
{
    [DbContext(typeof(MyAMISContext))]
    partial class MyAMISContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyAMIS.Core.Entidades.AccionAuditoria", b =>
                {
                    b.Property<int>("idAccionAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idAccionAuditoria"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idAccionAuditoria");

                    b.ToTable("AccionAuditoria");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.Activo", b =>
                {
                    b.Property<int>("idActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idActivo"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("codigoArea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("costoCompra")
                        .HasColumnType("numeric");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("estadoActivold")
                        .HasColumnType("integer");

                    b.Property<string>("marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("tipoActivold")
                        .HasColumnType("integer");

                    b.HasKey("idActivo");

                    b.HasIndex("estadoActivold");

                    b.HasIndex("tipoActivold");

                    b.ToTable("Activo");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.AuditoriaActivo", b =>
                {
                    b.Property<int>("idAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idAuditoria"));

                    b.Property<int>("accionAuditoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("activoId")
                        .HasColumnType("integer");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("usuarioId")
                        .HasColumnType("integer");

                    b.HasKey("idAuditoria");

                    b.HasIndex("accionAuditoriaId");

                    b.HasIndex("activoId");

                    b.ToTable("AuditoriaActivo");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.DepreciacionActivo", b =>
                {
                    b.Property<int>("idDepreciacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idDepreciacion"));

                    b.Property<int>("activoId")
                        .HasColumnType("integer");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("depreciacionAcumulada")
                        .HasColumnType("numeric");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaCalculo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("metodoDepreciacionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("valorActual")
                        .HasColumnType("numeric");

                    b.HasKey("idDepreciacion");

                    b.HasIndex("activoId");

                    b.HasIndex("metodoDepreciacionId");

                    b.ToTable("DepreciacionActivo");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.Diagnostico", b =>
                {
                    b.Property<int>("idDiagnostico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idDiagnostico"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("mantenimientoId")
                        .HasColumnType("integer");

                    b.HasKey("idDiagnostico");

                    b.HasIndex("mantenimientoId");

                    b.ToTable("Diagnostico");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.DocumentoActivo", b =>
                {
                    b.Property<int>("idDocumentoActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idDocumentoActivo"));

                    b.Property<int>("activoId")
                        .HasColumnType("integer");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("mantenimientoId")
                        .HasColumnType("integer");

                    b.Property<string>("referenciaDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("tipoDocumentoId")
                        .HasColumnType("integer");

                    b.HasKey("idDocumentoActivo");

                    b.HasIndex("activoId");

                    b.HasIndex("mantenimientoId");

                    b.HasIndex("tipoDocumentoId");

                    b.ToTable("DocumentoActivo");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.EstadoActivo", b =>
                {
                    b.Property<int>("idEstadoActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idEstadoActivo"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idEstadoActivo");

                    b.ToTable("EstadoActivo");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.EstadoFalla", b =>
                {
                    b.Property<int>("idEstadoFalla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idEstadoFalla"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idEstadoFalla");

                    b.ToTable("EstadoFalla");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.EstadoMantenimiento", b =>
                {
                    b.Property<int>("idEstadoMantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idEstadoMantenimiento"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idEstadoMantenimiento");

                    b.ToTable("EstadoMantenimiento");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.Falla", b =>
                {
                    b.Property<int>("idFalla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idFalla"));

                    b.Property<int>("activoId")
                        .HasColumnType("integer");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("estadoFallaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fechaReporte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("prioridadFallaId")
                        .HasColumnType("integer");

                    b.HasKey("idFalla");

                    b.HasIndex("activoId");

                    b.HasIndex("estadoFallaId");

                    b.HasIndex("prioridadFallaId");

                    b.ToTable("Falla");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.Mantenimiento", b =>
                {
                    b.Property<int>("idMantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idMantenimiento"));

                    b.Property<int>("activoId")
                        .HasColumnType("integer");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("estadoMantenimientoId")
                        .HasColumnType("integer");

                    b.Property<int?>("fallaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("fechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("tecnicoId")
                        .HasColumnType("integer");

                    b.Property<int>("tipoMantenimientoId")
                        .HasColumnType("integer");

                    b.HasKey("idMantenimiento");

                    b.HasIndex("activoId");

                    b.HasIndex("estadoMantenimientoId");

                    b.HasIndex("fallaId");

                    b.HasIndex("tipoMantenimientoId");

                    b.ToTable("Mantenimiento");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.MantenimientoRepuesto", b =>
                {
                    b.Property<int>("idMantenimientoRepuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idMantenimientoRepuesto"));

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("mantenimientoId")
                        .HasColumnType("integer");

                    b.Property<int>("repuestoId")
                        .HasColumnType("integer");

                    b.HasKey("idMantenimientoRepuesto");

                    b.HasIndex("mantenimientoId");

                    b.ToTable("MantenimientoRepuesto");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.MetodoDepreciacion", b =>
                {
                    b.Property<int>("idMetodoDepreciacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idMetodoDepreciacion"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idMetodoDepreciacion");

                    b.ToTable("MetodoDepreciacion");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.MovimientoActivo", b =>
                {
                    b.Property<int>("idMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idMovimiento"));

                    b.Property<int>("activoId")
                        .HasColumnType("integer");

                    b.Property<int>("areaDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("areaOrigenId")
                        .HasColumnType("integer");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaMovimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("responsableId")
                        .HasColumnType("integer");

                    b.HasKey("idMovimiento");

                    b.HasIndex("activoId");

                    b.ToTable("MovimientoActivo");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.PrioridadFalla", b =>
                {
                    b.Property<int>("idPrioridadFalla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idPrioridadFalla"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idPrioridadFalla");

                    b.ToTable("PrioridadFalla");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.TipoActivo", b =>
                {
                    b.Property<int>("idTipoActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTipoActivo"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idTipoActivo");

                    b.ToTable("TipoActivo");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.TipoDocumento", b =>
                {
                    b.Property<int>("idTipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTipoDocumento"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idTipoDocumento");

                    b.ToTable("TipoDocumento");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.TipoMantenimiento", b =>
                {
                    b.Property<int>("idTipoMantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTipoMantenimiento"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idTipoMantenimiento");

                    b.ToTable("TipoMantenimiento");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.Activo", b =>
                {
                    b.HasOne("MyAMIS.Core.Entidades.EstadoActivo", "EstadoActivo")
                        .WithMany("Activos")
                        .HasForeignKey("estadoActivold")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAMIS.Core.Entidades.TipoActivo", "TipoActivo")
                        .WithMany("Activos")
                        .HasForeignKey("tipoActivold")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoActivo");

                    b.Navigation("TipoActivo");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.AuditoriaActivo", b =>
                {
                    b.HasOne("MyAMIS.Core.Entidades.AccionAuditoria", "AccionAuditoria")
                        .WithMany("Auditorias")
                        .HasForeignKey("accionAuditoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAMIS.Core.Entidades.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("activoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccionAuditoria");

                    b.Navigation("Activo");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.DepreciacionActivo", b =>
                {
                    b.HasOne("MyAMIS.Core.Entidades.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("activoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAMIS.Core.Entidades.MetodoDepreciacion", "MetodoDepreciacion")
                        .WithMany("Depreciaciones")
                        .HasForeignKey("metodoDepreciacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("MetodoDepreciacion");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.Diagnostico", b =>
                {
                    b.HasOne("MyAMIS.Core.Entidades.Mantenimiento", "Mantenimiento")
                        .WithMany()
                        .HasForeignKey("mantenimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mantenimiento");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.DocumentoActivo", b =>
                {
                    b.HasOne("MyAMIS.Core.Entidades.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("activoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAMIS.Core.Entidades.Mantenimiento", "Mantenimiento")
                        .WithMany()
                        .HasForeignKey("mantenimientoId");

                    b.HasOne("MyAMIS.Core.Entidades.TipoDocumento", "TipoDocumento")
                        .WithMany("DocumentoActivos")
                        .HasForeignKey("tipoDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("Mantenimiento");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.Falla", b =>
                {
                    b.HasOne("MyAMIS.Core.Entidades.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("activoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAMIS.Core.Entidades.EstadoFalla", "EstadoFalla")
                        .WithMany("Fallas")
                        .HasForeignKey("estadoFallaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAMIS.Core.Entidades.PrioridadFalla", "PrioridadFalla")
                        .WithMany("Fallas")
                        .HasForeignKey("prioridadFallaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("EstadoFalla");

                    b.Navigation("PrioridadFalla");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.Mantenimiento", b =>
                {
                    b.HasOne("MyAMIS.Core.Entidades.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("activoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAMIS.Core.Entidades.EstadoMantenimiento", "EstadoMantenimiento")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("estadoMantenimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAMIS.Core.Entidades.Falla", "Falla")
                        .WithMany()
                        .HasForeignKey("fallaId");

                    b.HasOne("MyAMIS.Core.Entidades.TipoMantenimiento", "TipoMantenimiento")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("tipoMantenimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("EstadoMantenimiento");

                    b.Navigation("Falla");

                    b.Navigation("TipoMantenimiento");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.MantenimientoRepuesto", b =>
                {
                    b.HasOne("MyAMIS.Core.Entidades.Mantenimiento", "Mantenimiento")
                        .WithMany()
                        .HasForeignKey("mantenimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mantenimiento");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.MovimientoActivo", b =>
                {
                    b.HasOne("MyAMIS.Core.Entidades.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("activoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activo");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.AccionAuditoria", b =>
                {
                    b.Navigation("Auditorias");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.EstadoActivo", b =>
                {
                    b.Navigation("Activos");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.EstadoFalla", b =>
                {
                    b.Navigation("Fallas");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.EstadoMantenimiento", b =>
                {
                    b.Navigation("Mantenimientos");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.MetodoDepreciacion", b =>
                {
                    b.Navigation("Depreciaciones");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.PrioridadFalla", b =>
                {
                    b.Navigation("Fallas");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.TipoActivo", b =>
                {
                    b.Navigation("Activos");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.TipoDocumento", b =>
                {
                    b.Navigation("DocumentoActivos");
                });

            modelBuilder.Entity("MyAMIS.Core.Entidades.TipoMantenimiento", b =>
                {
                    b.Navigation("Mantenimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
